{"name": "test_create_other_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/juan/Desktop/users.json'", "trace": "def test_create_other_user():\n        #Read input json file\n>       file = open('/Users/juan/Desktop/users.json','r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/juan/Desktop/users.json'\n\nTestCases/test_CreateUser.py:27: FileNotFoundError"}, "start": 1682543135754, "stop": 1682543135754, "uuid": "4e52f1c7-cae4-4b20-a840-7466d1fdaf83", "historyId": "4f6164ba7a35c1c6b08a01de35c2e299", "testCaseId": "7d83058c0d497e85ccdcc9dd9b8c80a8", "fullName": "TestCases.test_CreateUser#test_create_other_user", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_CreateUser"}, {"name": "host", "value": "Juans-Mac-mini.local"}, {"name": "thread", "value": "6732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_CreateUser"}]}